baseURL: 'https://mixedconclusions.com'
languageCode: en-ca
title: Mixed Conclusions
theme: PaperMod
copyright: Andrew Wong - All Rights Reserved.
params:
  logo: /images/test_icon.png
  description: test description
  defaultTheme: dark
  homeInfoParams:
    Title: Hello! 😃
    Content: "My name is Andrew K.O. Wong.
    I'm a cell biologist by training,
    but these days I'm much more interested in data science.
    Below are posts about some of my personal data analysis/data science projects.
    Happy reading!
    "
  author: Andrew Wong
  ShowReadingTime: true
  ShowWordCount: true
  social:
    github: andrewKOwong
    linkedin: akowong
menu:
  main:
    - name: Blog
      weight: 100
      identifier: blog
      url: /blog
    - name: About Me
      identifier: about
      weight: 100
      url: /
